# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  condition: succeeded()

  jobs:
  - job: DeployWebApp
    displayName: 'Deploy to Azure Web App'

    steps:
    - download: current
      artifact: drop

    - task: AzureWebApp@1
      displayName: 'Deploy Azure Web App'
      inputs:
        azureSubscription: 'Azure subscription 1'
        appType: 'webApp'
        appName: 'DevOps'
        package: '$(Pipeline.Workspace)/drop/**/*.zip'

